enum AllUsersActionTypes {
    ALL_USERS_REQUEST_DATA = "ALL_USERS_REQUEST_DATA",
    ALL_USERS_LOAD_DATA = "ALL_USERS_LOAD_DATA",
    ALL_USERS_SELECT_EDITING_INDEX = "ALL_USERS_SELECT_EDITING_INDEX",
};

export default AllUsersActionTypes;